// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT7-17vc3GtP5aruwu22uFcBk8COQqLYE',
    appId: '1:30813224455:web:0aa7c97a4635b2c85f34a2',
    messagingSenderId: '30813224455',
    projectId: 'appointment-app-bcc0b',
    authDomain: 'appointment-app-bcc0b.firebaseapp.com',
    storageBucket: 'appointment-app-bcc0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcJ4eNfu9xJSj1wF3m_5L5RPavogT2HIg',
    appId: '1:30813224455:android:cdc1cf892b11463b5f34a2',
    messagingSenderId: '30813224455',
    projectId: 'appointment-app-bcc0b',
    storageBucket: 'appointment-app-bcc0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrkRhZq82VxYhbJY5R-SrUuwTvlum1Pbs',
    appId: '1:30813224455:ios:791ad17185c1fa7a5f34a2',
    messagingSenderId: '30813224455',
    projectId: 'appointment-app-bcc0b',
    storageBucket: 'appointment-app-bcc0b.appspot.com',
    iosClientId: '30813224455-q945dbblkutj96micm11l24puksu64b8.apps.googleusercontent.com',
    iosBundleId: 'com.example.appointmentApp',
  );
}
